# Predikcija F1 rezultata 2025-2026

Notebook je pregled rezultata koje generiŠe `run_analysis.py`. Za potpunu reprodukciju prvo pokrenuti skriptu iz glavnog direktorija projekta.

In [1]:
from pathlib import Path
import json
import pandas as pd

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
OUT = ROOT / "outputs"
TABLES = OUT / "tables"
print(ROOT)

/mnt/data/F1_seminarski_projekat

## Opcionalno: ponovno pokretanje cijelog procesa

Ukloniti `#` samo kada želite ponovo trenirati model i izvršiti simulacije.

In [2]:
# import subprocess, sys
# subprocess.run([sys.executable, str(ROOT / "run_analysis.py"), "--project-root", str(ROOT)], check=True)

## Sažetak skupa podataka

In [3]:
inventory = pd.read_csv(TABLES / "dataset_inventory.csv")
inventory[["file", "rows", "columns", "min_year", "max_year"]]

                         file    rows  columns  min_year  max_year
0                circuits.csv      77        9       NaN       NaN
1     constructor_results.csv   12625        5       NaN       NaN
2   constructor_standings.csv   13391        7       NaN       NaN
3            constructors.csv     212        5       NaN       NaN
4        driver_standings.csv   34863        7       NaN       NaN
5                 drivers.csv     861        9       NaN       NaN
6               lap_times.csv  589081        6       NaN       NaN
7               pit_stops.csv   11371        7       NaN       NaN
8              qualifying.csv   10494        9       NaN       NaN
9                   races.csv    1125       18    1950.0    2024.0
10                results.csv   26759       18       NaN       NaN
11                seasons.csv      75        2    1950.0    2024.0
12         sprint_results.csv     360       16       NaN       NaN
13                 status.csv     139        2       NaN       NaN

In [4]:
quality = json.loads((TABLES / "data_quality_summary.json").read_text())
pd.Series(quality, name="value").to_frame()

                            value
source_start_year            1950
source_end_year              2024
source_races                 1125
source_result_rows          26759
source_drivers                861
source_constructors           211
duplicate_driver_race_rows     91
missing_finish_order            0
missing_driver_ref              0
missing_constructor_ref         0
missing_circuit_ref             0
model_min_year               2005
model_max_year               2024
model_rows                   8290
model_races                   394
model_drivers                 102
model_lineages                 20
grid_zero_rows               1638

## HronoloŠka validacija 2019-2024

In [5]:
backtest = pd.read_csv(TABLES / "backtest_by_year.csv")
backtest[["test_year", "model_rank_mae", "baseline_rank_mae", "model_winner_accuracy", "baseline_winner_accuracy"]]

   test_year  model_rank_mae  ...  model_winner_accuracy  baseline_winner_accuracy
0       2019        3.861905  ...               0.285714                  0.523810
1       2020        3.941176  ...               0.647059                  0.647059
2       2021        3.518182  ...               0.363636                  0.318182
3       2022        3.840909  ...               0.500000                  0.500000
4       2023        3.731818  ...               0.727273                  0.863636
5       2024        3.678497  ...               0.375000                  0.333333

[6 rows x 5 columns]

## Prognoza 2025. naspram stvarnog konačnog poretka

In [6]:
comparison_2025 = pd.read_csv(TABLES / "comparison_2025_driver_standings.csv")
comparison_2025[["driver_name", "predicted_position", "actual_position", "predicted_points", "actual_points", "absolute_rank_error"]].head(15)

        driver_name  predicted_position  ...  actual_points  absolute_rank_error
0      Lando Norris                   1  ...            423                    0
1    Max Verstappen                   4  ...            421                    2
2     Oscar Piastri                   2  ...            410                    1
3    George Russell                   5  ...            319                    1
4   Charles Leclerc                   3  ...            242                    2
5    Lewis Hamilton                   6  ...            156                    0
6    Kimi Antonelli                   7  ...            150                    0
7   Alexander Albon                  20  ...             73                   12
8      Carlos Sainz                  11  ...             64                    2
9   Fernando Alonso                   9  ...             56                    1
10  Nico Hulkenberg                  16  ...             51                    5
11     Isack Hadjar                  17  ...             51                    5
12   Oliver Bearman                  12  ...             41                    1
13      Liam Lawson                  14  ...             38                    0
14     Esteban Ocon                  13  ...             38                    2

[15 rows x 6 columns]

## Predsezonska prognoza 2026. naspram stanja nakon 13. utrke

In [7]:
comparison_2026 = pd.read_csv(TABLES / "comparison_2026_preseason_driver_standings_to_round13.csv")
comparison_2026[["driver_name", "predicted_position", "actual_position", "predicted_points", "actual_points", "absolute_rank_error"]].head(15)

          driver_name  predicted_position  ...  actual_points  absolute_rank_error
0      Kimi Antonelli                 6.0  ...            267                  5.0
1      George Russell                 4.0  ...            201                  2.0
2      Lewis Hamilton                 7.0  ...            191                  4.0
3        Lando Norris                 1.0  ...            171                  3.0
4     Charles Leclerc                 5.0  ...            155                  0.0
5      Max Verstappen                 3.0  ...            127                  3.0
6       Oscar Piastri                 2.0  ...            116                  5.0
7        Isack Hadjar                 8.0  ...             71                  0.0
8         Liam Lawson                13.0  ...             51                  4.0
9        Pierre Gasly                19.0  ...             41                  9.0
10     Arvid Lindblad                14.0  ...             29                  3.0
11   Franco Colapinto                21.0  ...             21                  9.0
12     Oliver Bearman                12.0  ...             18                  1.0
13  Gabriel Bortoleto                20.0  ...             10                  6.0
14    Nico Hulkenberg                15.0  ...              6                  0.0

[15 rows x 6 columns]

## Ažurirana projekcija konačnog poretka 2026.

In [8]:
nowcast = pd.read_csv(TABLES / "nowcast_2026_after_round13_driver_standings.csv")
nowcast[["predicted_position", "driver_name", "expected_points", "points_p10", "points_p90", "championship_probability"]].head(15)

    predicted_position        driver_name  ...  points_p90  championship_probability
0                    1     Kimi Antonelli  ...       451.0                  0.961667
1                    2     George Russell  ...       382.0                  0.036000
2                    3     Lewis Hamilton  ...       333.0                  0.001667
3                    4       Lando Norris  ...       322.0                  0.000667
4                    5    Charles Leclerc  ...       312.0                  0.000000
5                    6      Oscar Piastri  ...       246.0                  0.000000
6                    7     Max Verstappen  ...       239.0                  0.000000
7                    8       Isack Hadjar  ...       166.0                  0.000000
8                    9        Liam Lawson  ...       102.1                  0.000000
9                   10       Pierre Gasly  ...        89.0                  0.000000
10                  11     Arvid Lindblad  ...        73.0                  0.000000
11                  12   Franco Colapinto  ...        56.0                  0.000000
12                  13     Oliver Bearman  ...        48.0                  0.000000
13                  14  Gabriel Bortoleto  ...        32.0                  0.000000
14                  15    Nico Hulkenberg  ...        26.0                  0.000000

[15 rows x 6 columns]

## Kandidati za pobjede u preostalim utrkama

In [9]:
wins = pd.read_csv(TABLES / "nowcast_2026_remaining_top3_win_candidates.csv")
wins[["round", "race_name", "driver_name", "win_probability"]]

    round                       race_name      driver_name  win_probability
0      14              Spanish Grand Prix   Kimi Antonelli         0.237000
1      14              Spanish Grand Prix   George Russell         0.217667
2      14              Spanish Grand Prix  Charles Leclerc         0.150000
3      15           Azerbaijan Grand Prix   Kimi Antonelli         0.245333
4      15           Azerbaijan Grand Prix   George Russell         0.204667
5      15           Azerbaijan Grand Prix  Charles Leclerc         0.132333
6      16  Bahrain Grand Prix in Malaysia   Kimi Antonelli         0.242000
7      16  Bahrain Grand Prix in Malaysia   George Russell         0.199667
8      16  Bahrain Grand Prix in Malaysia  Charles Leclerc         0.138333
9      17            Singapore Grand Prix   Kimi Antonelli         0.224333
10     17            Singapore Grand Prix   George Russell         0.210333
11     17            Singapore Grand Prix     Lando Norris         0.124333
12     18        United States Grand Prix   Kimi Antonelli         0.249667
13     18        United States Grand Prix   George Russell         0.203667
14     18        United States Grand Prix  Charles Leclerc         0.128000
15     19          Mexico City Grand Prix   Kimi Antonelli         0.239333
16     19          Mexico City Grand Prix   George Russell         0.229667
17     19          Mexico City Grand Prix  Charles Leclerc         0.134667
18     20            Sao Paulo Grand Prix   Kimi Antonelli         0.212667
19     20            Sao Paulo Grand Prix   George Russell         0.196000
20     20            Sao Paulo Grand Prix  Charles Leclerc         0.135000
21     21            Las Vegas Grand Prix   Kimi Antonelli         0.251333
22     21            Las Vegas Grand Prix   George Russell         0.235667
23     21            Las Vegas Grand Prix  Charles Leclerc         0.142000
24     22                Qatar Grand Prix   Kimi Antonelli         0.235667
25     22                Qatar Grand Prix   George Russell         0.229333
26     22                Qatar Grand Prix  Charles Leclerc         0.149333
27     23            Abu Dhabi Grand Prix   George Russell         0.228667
28     23            Abu Dhabi Grand Prix   Kimi Antonelli         0.213000
29     23            Abu Dhabi Grand Prix     Lando Norris         0.137667